name: dartnissanconnect
description: A fork of Tobiaswks dartnissanconnect lib for the NissanConnect API.
version: 1.0.5
homepage: https://github.com/Derich367/dartnissanconnect

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: '^0.17.0'
  http: '^0.13.1'

dev_dependencies:
  test: '^1.3.0'
